name: thenews
description: A simple news app built with flutter and open news api

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  clock: ^1.1.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.1.0
  gallery_saver: ^2.3.2
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.6.0
  mocktail_image_network: ^0.3.1
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  hive_test: ^1.0.1
  http_mock_adapter: ^0.3.3
  json_serializable: ^6.3.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-light.ttf
          weight: 300
